# Generated by Django 5.0.6 on 2024-08-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodCatogory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cat_image', models.ImageField(upload_to='static/images/cat')),
                ('food_img', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Address', models.TextField()),
                ('rating', models.FloatField()),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_img', models.ImageField(upload_to='static/images/food')),
                ('food_link', models.CharField(max_length=1000)),
                ('most_of', models.BooleanField(default=False, help_text='0-default ,1-show')),
                ('rating', models.FloatField()),
                ('combo', models.BooleanField(default=False, help_text='0-default ,1-show')),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodcatogory')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
    ]
