# Generated by Django 3.2.11 on 2025-01-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(default='', upload_to='static/images/hotels'),
        ),
    ]
