# Generated by Django 3.2.11 on 2025-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='second_image',
            field=models.ImageField(default='', upload_to='static'),
        ),
    ]
